name: short
description: "Short It!"
version: 1.0.0+1

publish_to: 'none'
repository: https://github.com/pchkauu/want_short_app

environment:
  sdk: ^3.5.2

dependencies:
  auto_route: ^8.0.3
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  connecteo: ^3.0.0
  cupertino_icons: ^1.0.6
  dartx: ^1.2.0
  device_info_plus: ^11.1.0
  dio: ^5.4.2+1
  dio_smart_retry: ^6.0.0
  dotted_border: ^2.1.0
  either_dart: ^1.0.0
  equatable: ^2.0.5
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_flavor: ^3.1.3
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  flutter_svg_provider: ^1.0.7
  freezed_annotation: ^2.4.1
  get_it: ^8.0.1
  image_picker: ^1.1.2
  injectable: ^2.3.3
  internet_connection_checker_plus: ^2.5.1
  intl: ^0.19.0
  json_annotation: ^4.8.1
  meta: ^1.11.0
  path: ^1.9.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  rxdart: ^0.27.7
  sentry_dart_plugin: ^2.0.0
  sentry_dio: ^8.6.0
  sentry_flutter: ^8.6.0
  shared_preferences: ^2.2.2
  sound_mode: ^3.0.0
  sprung: ^3.0.1
  talker: ^4.1.3
  talker_bloc_logger: ^4.1.3
  talker_dio_logger: ^4.1.3
  talker_flutter: ^4.1.3
  uni_links3: ^0.5.3
  wakelock_plus: ^1.2.8
  webview_flutter: ^4.8.0

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  change_app_package_name: ^1.1.0
  flutter_gen_runner: ^5.8.0
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  injectable_generator: ^2.4.2
  json_serializable: ^6.7.1
  rename_app: ^1.3.2

flutter_gen:
  package_parameter_enabled: true
  output: lib/src/core/ui_kit/gen/
  line_length: 80

  integrations:
    flutter_svg: true

  colors:
    inputs:
      - asset/color/colors.xml


flutter:
  generate: true
  uses-material-design: true

  assets:
    - asset/
    - asset/app/
    - asset/color/
    - asset/font/
    - asset/font/unbounded/

  fonts:
    - family: Unbounded
      fonts:
        - asset: asset/font/unbounded/Unbounded-ExtraLight.ttf
          weight: 100
        - asset: asset/font/unbounded/Unbounded-Light.ttf
          weight: 200
        - asset: asset/font/unbounded/Unbounded-Light.ttf
          weight: 300
        - asset: asset/font/unbounded/Unbounded-Regular.ttf
          weight: 400
        - asset: asset/font/unbounded/Unbounded-Medium.ttf
          weight: 500
        - asset: asset/font/unbounded/Unbounded-SemiBold.ttf
          weight: 600
        - asset: asset/font/unbounded/Unbounded-Bold.ttf
          weight: 700
        - asset: asset/font/unbounded/Unbounded-ExtraBold.ttf
          weight: 800
        - asset: asset/font/unbounded/Unbounded-Black.ttf
          weight: 900
